// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Common.DALSql.Migrations
{
    [DbContext(typeof(ShipDbContext))]
    [Migration("20210716082225_AddPhoneNumberToUser")]
    partial class AddPhoneNumberToUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Common.DALSql.Entities.Token", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<DateTime>("ExpireAt")
                    .HasColumnType("timestamp without time zone");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.Property<long>("UserId")
                    .HasColumnType("bigint");

                b.Property<string>("Value")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Tokens");
            });

            modelBuilder.Entity("Common.DALSql.Entities.User", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Email")
                    .HasColumnType("text");

                b.Property<string>("FirstName")
                    .HasColumnType("text");

                b.Property<bool>("IsEmailVerified")
                    .HasColumnType("boolean");

                b.Property<string>("LastName")
                    .HasColumnType("text");

                b.Property<DateTime>("LastRequest")
                    .HasColumnType("timestamp without time zone");

                b.Property<bool>("OAuthGoogle")
                    .HasColumnType("boolean");

                b.Property<string>("PasswordHash")
                    .HasColumnType("text");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("text");

                b.Property<string>("ResetPasswordToken")
                    .HasColumnType("text");

                b.Property<string>("SignupToken")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Common.DALSql.Entities.Token", b =>
            {
                b.HasOne("Common.DALSql.Entities.User", "User")
                    .WithMany("Tokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("Common.DALSql.Entities.User", b =>
            {
                b.Navigation("Tokens");
            });
#pragma warning restore 612, 618
        }
    }
}